# Generated by Django 2.1.3 on 2018-12-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questiontechnology',
            fields=[
                ('technologyid', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, choices=[('MSSQL', 'SQL Server'), ('MySQL', 'MySQL'), ('Oracle', 'Oracle')], default='MSSQL', max_length=20, null=True)),
                ('subcategory', models.CharField(blank=True, choices=[('DEV', 'Development'), ('Admin', 'Administration'), ('Art', 'Architect')], default='Admin', max_length=20, null=True)),
                ('level', models.CharField(blank=True, choices=[('L1', 'Level 01 - Beginner'), ('L2', 'Level 02 - Intermediate'), ('L3', 'Level 03 - Expert'), ('L4', 'Level 04 - SME')], default='L2', max_length=8, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'QuestionTechnology',
                'managed': False,
            },
        ),
    ]
