# Generated by Django 2.1.3 on 2018-11-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backuphistory',
            fields=[
                ('backuphistid', models.AutoField(db_column='BackupHistId', primary_key=True, serialize=False)),
                ('instanceid', models.IntegerField(db_column='InstanceId')),
                ('databaseid', models.IntegerField(db_column='DatabaseId')),
                ('fullbackupdate', models.DateTimeField(blank=True, db_column='FullbackupDate', null=True)),
                ('diffbackupdate', models.DateTimeField(blank=True, db_column='DiffBackupDate', null=True)),
                ('tranbackupdate', models.DateTimeField(blank=True, db_column='TranBackupDate', null=True)),
                ('fullbackupsize', models.BigIntegerField(blank=True, db_column='FullBackupSize', null=True)),
                ('diffbackupsize', models.IntegerField(blank=True, db_column='DiffBackupSize', null=True)),
                ('tranbackupsize', models.IntegerField(blank=True, db_column='TranBackupSize', null=True)),
                ('fullbackupduration', models.IntegerField(blank=True, db_column='FullBackupDuration', null=True)),
                ('diffbackupduration', models.IntegerField(blank=True, db_column='DiffBackupDuration', null=True)),
                ('tranbackupduration', models.IntegerField(blank=True, db_column='TranBackupDuration', null=True)),
                ('compressed', models.BooleanField(blank=True, db_column='Compressed', null=True)),
            ],
            options={
                'db_table': 'BackupHistory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Backupschedule',
            fields=[
                ('bkuschedid', models.AutoField(db_column='BkuSchedId', primary_key=True, serialize=False)),
                ('instanceid', models.IntegerField(db_column='InstanceId')),
                ('databaseid', models.IntegerField(db_column='DatabaseId')),
                ('timefrom', models.DateTimeField(blank=True, db_column='TimeFrom', null=True)),
                ('timeto', models.DateTimeField(blank=True, db_column='TimeTo', null=True)),
            ],
            options={
                'db_table': 'BackupSchedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Databases',
            fields=[
                ('databaseid', models.AutoField(db_column='DatabaseId', primary_key=True, serialize=False)),
                ('instanceid', models.IntegerField(db_column='InstanceId')),
                ('databasename', models.CharField(db_column='DatabaseName', max_length=50)),
                ('createddate', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
                ('recoverymodel', models.CharField(blank=True, db_column='RecoveryModel', max_length=64, null=True)),
                ('currentdbsize', models.CharField(blank=True, db_column='CurrentDBSize', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Databases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('instanceid', models.AutoField(db_column='InstanceID', primary_key=True, serialize=False)),
                ('instancename', models.CharField(db_column='InstanceName', max_length=128)),
                ('serverid', models.IntegerField(db_column='ServerID')),
                ('port', models.CharField(blank=True, db_column='Port', max_length=8, null=True)),
                ('ipaddress', models.CharField(blank=True, db_column='IPAddress', max_length=15, null=True)),
                ('sqlserviceaccountid', models.IntegerField(blank=True, db_column='SQLServiceAccountID', null=True)),
                ('authenticationmode', models.BooleanField(blank=True, db_column='AuthenticationMode', null=True)),
                ('saaccountname', models.CharField(blank=True, db_column='saAccountName', max_length=128, null=True)),
                ('saaccountpassword', models.CharField(blank=True, db_column='saAccountPassword', max_length=64, null=True)),
                ('instanceclassification', models.SmallIntegerField(blank=True, db_column='InstanceClassification', null=True)),
                ('instancecores', models.SmallIntegerField(blank=True, db_column='InstanceCores', null=True)),
                ('instanceram', models.BigIntegerField(blank=True, db_column='InstanceRAM', null=True)),
                ('sqlserveragentaccountid', models.IntegerField(blank=True, db_column='SQLServerAgentAccountID', null=True)),
                ('defaultbkupath', models.CharField(blank=True, db_column='DefaultBkuPath', max_length=250, null=True)),
                ('defaultbkupathsize', models.CharField(blank=True, db_column='DefaultBkuPathSize', max_length=20, null=True)),
                ('defaultbkupathfree', models.CharField(blank=True, db_column='DefaultBkuPathFree', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Instance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('serverid', models.IntegerField(db_column='ServerID', primary_key=True, serialize=False)),
                ('server', models.CharField(blank=True, db_column='Server', max_length=128, null=True)),
                ('domain', models.CharField(blank=True, db_column='Domain', max_length=25, null=True)),
                ('servertype', models.CharField(blank=True, db_column='ServerType', max_length=50, null=True)),
                ('shortdescription', models.CharField(blank=True, db_column='ShortDescription', max_length=128, null=True)),
                ('sqlstate', models.CharField(blank=True, db_column='SQLState', max_length=20, null=True)),
                ('category', models.CharField(blank=True, db_column='Category', max_length=20, null=True)),
                ('businessunit', models.CharField(blank=True, db_column='BusinessUnit', max_length=20, null=True)),
                ('os', models.CharField(blank=True, db_column='OS', max_length=64, null=True)),
                ('sqlversion', models.CharField(blank=True, db_column='SQLVersion', max_length=64, null=True)),
                ('sockets', models.IntegerField(blank=True, db_column='Sockets', null=True)),
                ('cores', models.IntegerField(blank=True, db_column='Cores', null=True)),
                ('logicalprocs', models.IntegerField(blank=True, db_column='LogicalProcs', null=True)),
                ('businessowner', models.CharField(blank=True, db_column='Businessowner', max_length=25, null=True)),
                ('technicalowner', models.CharField(blank=True, db_column='TechnicalOwner', max_length=25, null=True)),
                ('secondarytechnicalowner', models.CharField(blank=True, db_column='SecondaryTechnicalOwner', max_length=25, null=True)),
                ('additionalnotes', models.TextField(blank=True, db_column='AdditionalNotes', null=True)),
                ('backuppsdeployed', models.BooleanField(blank=True, db_column='BackupPSDeployed', null=True)),
            ],
            options={
                'db_table': 'Server',
                'managed': False,
            },
        ),
    ]
