# Generated by Django 2.1.3 on 2018-12-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commandqueue',
            fields=[
                ('guid', models.CharField(db_column='GUID', max_length=254)),
                ('command', models.TextField(db_column='Command')),
                ('jobid', models.CharField(blank=True, db_column='jobId', max_length=50, null=True)),
                ('jobtype', models.CharField(db_column='JobType', max_length=20)),
                ('status', models.CharField(db_column='Status', max_length=10)),
                ('reason', models.TextField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'CommandQueue',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('databaseid', models.AutoField(db_column='DatabaseId', primary_key=True, serialize=False)),
                ('databasename', models.CharField(db_column='DatabaseName', max_length=50)),
                ('createddate', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
                ('recoverymodel', models.CharField(blank=True, db_column='RecoveryModel', max_length=64, null=True)),
                ('currentdbsize', models.CharField(blank=True, db_column='CurrentDBSize', max_length=10, null=True)),
                ('backuppath', models.CharField(blank=True, db_column='BackupPath', max_length=128, null=True)),
            ],
            options={
                'db_table': 'Databases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Logging',
            fields=[
                ('logid', models.AutoField(db_column='logId', primary_key=True, serialize=False)),
                ('logmessage', models.TextField(db_column='LogMessage')),
            ],
            options={
                'db_table': 'Logging',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Questiontechnology',
            fields=[
                ('technologyid', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=20, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'QuestionTechnology',
                'managed': False,
            },
        ),
    ]
